- name: Directories are present
  file:
    dest: "{{ item }}"
    state: directory
  with_items: directories
  tags: [consul]

- name: Files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: files
  tags: [consul]

- name: Upstart script is present
  template:
    src: consul.conf.j2
    dest: /etc/init/consul.conf
    mode: 0644
  tags: [consul]

- name: Service is started
  service:
    name=consul
    state=started
    pattern=/usr/local/bin/consul
  tags: [consul]

- name: Node is in cluster
  shell: consul join {{ consul_master_ip }}
  when: consul_master_ip is defined
  tags: [consul]

- name: Configurations are present
  template:
    src: consul_check.json.j2
    dest: /etc/consul.d/consul_check.json
  register: result
  with_items: consul_nodes
  tags: [consul]

- name: Consul is restarted
  shell: killall -HUP consul
  when: result|changed
  tags: [consul]