- hosts: service
  remote_user: vagrant
  sudo: yes
  vars:
    - container_image: vfarcic/books-service
    - container_name: books-service
    - container_internal_port: 8080
    - container_volumes: none
    - container_blue_port: 9001
    - container_green_port: 1{{ container_blue_port }}
    - container_envs: none
    - container_db_image: mongo
    - container_db_name: "{{ container_name }}-db"
    - container_db_internal_port: 27017
    - container_db_volumes: '"-v /data/{{ container_db_name }}:/data/db"'
    - container_db_port: 2{{ container_blue_port }}
    - http_address: /api/v1/books
  roles:
    - docker
    - nginx
    - service