blue:
  ports:
    - 8080
  environment:
    - SERVICE_NAME=books-fe-blue
  image: vfarcic/books-fe
green:
  ports:
    - 8080
  environment:
    - SERVICE_NAME=books-fe-green
  image: vfarcic/books-fe